---

- name: Install the postgresql apt repo key
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Make sure we have the postgresql apt repo installed
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
    state: present
    update_cache: yes

- name: Install postgresql & dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - "postgresql-{{ postgresql.version }}"
    - "postgresql-contrib-{{ postgresql.version }}"
    - python-psycopg2
